apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf
  labels:
    app: {{ .Release.Name }}
data:
  file: |
    Hello from ConfigMap!
    This content is served at /conf/file
  settings.yaml: |
    app: homework
    env: prod
