apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---
# Даём права admin внутри ТОЛЬКО этого namespace через RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin     # встроенный кластерный роль-пресет
