apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      nodeSelector:
        homework: "true"
      volumes:
      - name: shared
        emptyDir: {}           # общий временный том между init и основным контейнером

      initContainers:
        - name: init-index
          image: busybox:1.36
          command:
            - wget
            - "-O"
            - "/init/index.html"
            - "http://otus.ru"
          volumeMounts:
            - name: shared
              mountPath: /init          # путь для init-контейнера

      containers:
        - name: web
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              # Запуск простого веб-сервера busybox на 8000 порту
              httpd -f -p 8000 -h /homework
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: shared
              mountPath: /homework      # тот же том для основного контейнера
          readinessProbe:
            exec:
              command:
                - cat
                - /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - rm -f /homework/index.html   # удалить файл перед завершением