apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  storageClassName: sc-homework
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
